### ISSUE TITLE
blog and post pages need work to pass validation of schema.org structured data

### ISSUE THREAD

**Issue by CrispinF** [joeaudette/cloudscribe.SimpleContent#105]
The google structured data testing tool reports 9 errors and 6 warnings on the root blog page at https://historicplacenames.rcahmw.gov.uk/blog 

On an individual post it reports 3 errors and 2 warnings.

**Comment by joeaudette** [comment]
thanks, will look into this soon. it appears the 3 errors and 2 warnings on a single post are the same ones reported on the post list, they are just repeated there per post.

**Comment by joeaudette** [comment]
this is now fixed in the latest nugets.

note that for pages and posts the first image in the content is extracted as the image for schema.org meta data so there could still be errors reported if the content doesn't have an image.

note also that there are new "Content Settings" for publisher and publisher logo which must be populated to resolve the errors.

there still remains a warning about mainEntityOfPage but that is a content specific thing that could never be determined automatically and may often not be applicable for every page or post which is probably why it is only a warning. If the content author knows about a specific entity that the post or page is about, meta data could be added manually to the post or page in source view
