### ISSUE TITLE
I can't edit pages or post!

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe.SimpleContent#2]
> After you login a little pencil will appear in the upper right corner, it toggles the editor toolbar.

But it doesn't appears for me.I try it with chrome developer the following resources not found, may be this errors cause I can't see the edit button?
```
http://localhost:60000/js/bootstrap-wysiwyg.js 
http://localhost:60000/js/content-editor.js
http://localhost:60000/jsdev/site.js 
```

**Comment by joeaudette** [comment]
my plan is that js will be the production version of files and jsdev is the dev version. Things are configured to use jsdev when the environment is set to Development and js when the environment is set to Production. However, I have not yet done the work to process anything into the js folder ie I have not done any work in gulp/grunt yet so currently it only works with the environment set to Development

**Comment by mikeandersun** [comment]
The jsdev  not exists in wwwroot. 
wwwroot is ignored by git.

**Comment by joeaudette** [comment]
Thanks! you were right, actually the scripts exist in the wwwroot/js folder on my local machine and that folder is excluded from git because that is where the js should be processed into. 

I have copied them to jsdev which is where they should be, it was my mistake. This is fixed and [those scripts exist now now in the repo](https://github.com/joeaudette/cloudscribe.SimpleContent/tree/master/src/example.WebApp/wwwroot/jsdev) 

please try again and let me know if you have any trouble, I am surprised no-one has told me about this until now

**Comment by mikeandersun** [comment]
It work now. 
Thanks
