### ISSUE TITLE
User account link not functioning / not implemented?

### ISSUE THREAD

**Issue by CrispinF** [joeaudette/cloudscribe.SimpleContent#22]
Looks like this area just not implemented yet, so I'm sure you know about this, but the "Hello Bilbo Baggins" link https://localhost:44348/Account/Index  goes nowhere (or rather, seems to try to create new page) - no Accounts controller. The link seems to come from _LoginPartial.cshtml

**Comment by joeaudette** [comment]
that was a bug in the view for SimpleAuth which has no user account page, so there should not ahve been a link there, I've fixed that bug but I've also merged my current work to the master branch which changes the example.WebApp proejct from using SimpleAuth to using cloudscribe Core, in cloudscribe Core there does exist a user account page. I deleted the _LoginPartial from the samples folder demo that uses SimpleAuth so that it will instead use the fixed one that is embedded in the simpleauth nuget
