### ISSUE TITLE
Proposal for teaser functionality

### ISSUE THREAD

**Issue by JacobsDataSolutions** [joeaudette/cloudscribe.SimpleContent#226]
For the blog projects I'm working on, I anticipate posting a lot of content that is text-heavy (blog entries of several thousand words, fiction, etc). For my purposes I require "teaser" functionality on the Index view of the blog, similar to other CMS systems like Drupal, Wordpress, etc that truncate the post content for display on the listing page.

The way I'm currently envisioning this is as follows:
- Auto-teaser mode: On/Off setting for the project settings i.e. site-wide that automatically manipulate the content of posts. If enabled, the following additional settings would apply: Truncation length (integer). Truncation mode (enum): characters/words/paragraphs. A naive implementation could just use HtmlAgilityPack or similar library to strip all tags from the content when working out the teaser. Then use Humanizer to truncate it in a somewhat smart way. This would be fine for my needs.
- Explicit teaser: Additional property of PostEntity/IPost that specifies what the teaser should be for an individual post. This will override any other teaser calculated for the post, regardless of whether auto-teaser mode is on/off.

That's about it. Another approach would be to reverse engineer Wordpress or Drupal and just see how they do it. Also, you mentioned using HTML comments embedded in the text itself. I'm OK evaluating this approach if it doesn't involve too many moving pieces. I'm not very familiar with CKeditor extensions at this point, so I don't have a clear idea of the effort involved. I reviewed the contribution guidelines and I'm OK assigning copyright for any work I do. Thanks Joe!

**Comment by joeaudette** [comment]
Your proposal sounds good! Thanks for your offer to help! I think we can go with your idea instead of the idea with an html comment and an editor plugin. It will be even better if the user doesn't have to do anything but can override with an explicit teaser if they want to. I think the teaser should probably support html editor just the same as the main content. We could limit the the length but probably should let them put whatever they want and not limit it, but we can indicate in the label/tooltip that if provided it should be short compared to the main content. We can probably add a tabbed ui in the post edit similar as we have for pages and put the teaser out of the way in the other tab.

To get the administrative part out of the way please print and sign the [copyright agreement](https://github.com/joeaudette/cloudscribe/blob/master/copyright-assignment.txt) and scan it as pdf and email it to me at joe dot audette a g mail dot com, or mail it to PO Box 1978, Concord, NC 28026

SimpleContent already depends on cloudscribe.HtmlAgilityPack which is a port of HtmlAgilityPack to .NET Core, I have not looked to see if there is a more official port now, there wasn't at the time when I first needed it but if there is now we can switch to that one, otherwise you can use the same one.

**Comment by JacobsDataSolutions** [comment]
Sounds good. How did you want to have me deliver my work? Is it possible for you to create a branch off the SimpleContent master and grant me contribute access to only that branch? Or do you want me to create a branch off my fork and then create a pull request when I'm done? I'm relatively new to all of this. Thanks!

**Comment by joeaudette** [comment]
If you fork this repo there should already be a dev branch in your fork. I would work in the dev branch of your fork and then when ready can make the pull request back against the dev branch in this repository.

**Comment by JacobsDataSolutions** [comment]
OK, I'll give it a shot.

**Comment by joeaudette** [comment]
Hi John,

Thanks for your work and for sending the copyright agreement!
Reviewing the code I see a couple of things I would like changed before you submit the pull request and have some questions.

Q: What is the AddThisMetaData and IAddThisMetaData stuff? That was not in the original proposal. Support for AddThis sharing is already in cloudscribe Core. All you have to do is put the AddThisProfileId in SiteSettings and it should just work.

It looks like a lot of my wild card project version references were changed to specific version references.  Also a project reference for cloudscribe.SimpleContent.Web was added to the bootstrap project which isn't needed since the views are just embedded resources. Not a big deal as I can change those back. Actually hoping in ASP.NET Core 2.1 there will be support for pre-compiled views in class libraries then I will have to revisit the need for references.

I would prefer not to have a maxlength on TeaserOverride, while it should be conceptually shorter than the main post I don't think we should enforce it or block someone form entering content longer than 2000 chars.

Seems like TeaserPartial.cshtml replicates a lot of markup that then has to be maintained in multiple views. Can't this be simplified if we are just swapping the rendering of the main content with the teaser content?

Why does post have both DisplayAutoTeaser and SuppressAutoTeaser? That seems confusing from a UX point of view. Seems like setting DisplayAutoTeaser to false would be equivalent to SuppresAutoTeaser = true.

I think it would be better if TeaserService was an injected implementation of an interface ITeaserService, and change it to pass in the model to a method rather than the constructor. That way it would be possible to inject a different implementation and it would be more testable, and there could be an alternate DoNothingTeaserService that just returns the raw post so people could turn that off completely if they wanted to just by injecting the alternate. I'm sure the implementation does a reasonable job of not leaving unclosed tags. I don't do TDD per se but I try to keep code testable and if bug reports come in about the truncation, then it would be possible to write a unit test that replicates the bug and then fix it, or even replace the implementation altogether. Both IProjectSettings and IPost could be passed into the methods on ITeaserService. It could be reduced to a single Method CreateTeaserIfNeeded which returns either a teaser or the full post if not needed. Then less conditionals are needed in the view as well. To simplify the views and not have duplicated markup, the BogViewModel could have a property for ITeaserService, so it could be injected in the controller and assigned to the model. That would eliminate the need for TeaserPartial, and PostPartial could just have something like this:

    <div itemprop="articleBody">@Html.Raw(Model.FilterHtml(Model.TeaserService.CreateTeaserIfNeeded(Model.ProjectSettings,Model.TmpPost)))</div>

Actually on second thought we need to also consider how this plays with markdown content type. So really I think what we need is to get rid of TeaserPartial, revert PostPartial so it only calls Model.FilterHtml, then use ITeaserService inside the Model.FilterHtml  method AFTER filtering so that the teaser would be generated after the markdown is converted to html. But since FilterHtml is used also on post detail where we don't want a teaser, I think we need a new method for use on the list that would look something like this:

    public string FilterHtmlForList(IPost p)
    {
	var html = _contentProcessor.FilterHtml(p, ProjectSettings);  
        return _teaserService.CreateTeaserIfNeeded(ProjectSettings, p, html);	
     }

The important point being that though we would pass in the IPost so the properties would be detected, we would pass in the html that may or may not have been converted from markdown and use that to create the teaser if needed.

So PostPartial would call Model.FilterHtmlForList and that would be the only change needed and we would not need TeaserPartial

**Comment by JacobsDataSolutions** [comment]
- Regarding the AddThisMetaData and IAddThisMetaData files, I didn't realize that you basically had all of this functionality built in when I added those. There is one minor tweak that I made to SimpleContent that makes sense for my customized fork, which is to use the Image property of ProjectSettings to force the og:image meta tag to show an image of my choosing, even if the user isn't browsing a content page.
- For the project versions, I sort of hacked up my fork so that I could have all projects in the solution open in Visual Studio at the same time while I work. I'm new to using Github, so I'm kind of confused as to how you work against different components (ie - Core, SimpleContent) while still compiling them to nuget packages. I'd be interested in finding out how you have that set up.

So to make a clean pull request, is there any way that you can just cherry pick the commits that are relevant only to this feature?

- For the max length on teaser, I'll go ahead and make the change.
- DisplayAutoTeaser and SuppressAutoTeaser are just different sides of the same coin. I wanted a way to force an auto teaser to appear, even if auto teaser mode is OFF. I also wanted a way to suppress a teaser for a given post, even if auto teaser mode is ON. However, I see your point that it can be confusing from a UX perspective. Let me know what you would prefer.
- For the teaser service, let me see if I can make that change and extract an interface for it.
- Ditto for the teaser partial view. I agree with you that it can be simplified.

**Comment by joeaudette** [comment]
Hi John,

I'm not aware of a way to pick and choose commits for a pull request so the goal should be to eliminate any unwanted changes before making the pull request. However if some minor unwanted changes come along for the ride I can change them back after merging.

Not sure what you mean about having to hack the projects together for your fork. All the SimpleContent projects are already in the solution, you should not need the source for any other external projects ie cloudscribe Core, the nuget dependencies should be fine for that. Maybe explain what projects you mean you had to add and why? To test the different data layers from the sourceDev.WebApp only requires making changes in appsettings then building the solution.

Basically every project in the solution except the sourceDev.WebApp correspond to nuget packages. I just increment the version in the .csproj files for any projects with changes, then rebuild in release mode then right click each project and choose "Pack" and that makes a new nuget package. But you should not need to do that since I will be the one publishing the nugets.

While it is up to you if you want to have a custom fork long term, my advice would be not to. Even if there are things you want that we don't come to agreement on, almost anything can be done in your own separate projects without need of a fork. The main purpose of a fork is for the purpose of getting changes accepted back into the project, I would not recommend for anyone to maintain a fork and just customize away long term. If there is something you need that you think can only be done by keeping a fork long term let me know and maybe I will have some ideas to solve the problem without doing that.


### From my point of view the changes needed in your fork before making a pull request are:

Remove AddThisMetaData and IAddThisMetaData unless you would like to make the case why they are still needed. I'm ok with the change in the view to pass in the projectsettings image as a default to use if no image is found.

Remove the maxlength of the teaser.

I don't think we need a way to force a teaser on a specific post if teasers are disabled. I think it is sufficient to have one setting for disabling teaser on a post if teasers are enabled from projectsettings.

Refactor the TeaserSerivce so it is an injectable interface passed into the BlogViewModel from controller and add a method in the viewmodel that looks like this:

   public string FilterHtmlForList(IPost p)
    {
        var html = _contentProcessor.FilterHtml(p, ProjectSettings);  
        return _teaserService.CreateTeaserIfNeeded(ProjectSettings, p, html);	
    }

so only one method is needed on the ITeaserService

TeaserPartial can go away. PostPartial can be changed to call the new FilterForList method on the view model

If you are agreeable to all that just let me know when you are ready for me to review it again.

Many thanks for your work!

**Comment by JacobsDataSolutions** [comment]
I took your advice and blew away my forks, then re-forked SimpleContent from your repo. I reapplied my changes and I'm now in the process of writing a couple of unit tests. I should be done in the next day or so. Thanks again.

**Comment by JacobsDataSolutions** [comment]
Hey Joe, I finished my work on this feature. When you get a chance can you please look at my fork of SimpleContent. My stuff is checked into the Feature-BlogTeasers branch. Let me know if this is ready for a pull request or if there are other changes you'd recommend. Thanks.

**Comment by joeaudette** [comment]
Hi John,

That is great! Thanks! I'm travelling at the moment, over in Wales in the UK, so may not get a chance to review it until I get back next Thursday. I would say go ahead and make a pull request and then if it all looks good which I think it probably will I can accept it right after reviewing. 

Thanks,

Joe

**Comment by joeaudette** [comment]
Hi John,

Sorry it is taking me sol long, I'm very busy with client project work.
From initial testing the the branch where I merged it, I experimented with various teaser settings. Seemed ok at first but then I tried characters as truncation mode and 400 as max chars and noticed a problem in one of the posts in my dev environment. The "Show More" text was not a link, and upon inspection it was a malformed open link at the end of the truncated content that messed up the next we'l formed link in the razor view. I have a feeling the character truncation is more prone to that and not sure how to fix it.

I [added a failing test](https://github.com/joeaudette/cloudscribe.SimpleContent/blob/jonjacobs/test/cloudscribe.SimpleContent.Web.Tests/Services/TeaserServiceTests.cs) that demos the problem and asserts the rendered output doesn't equal the bad result, but not sure how it would be possible to fix it.

Any ideas how to fix it, or should we consider leaving out character truncation mode?

I still want to do more thorough testing on all the modes before merging but it may be next week as I'm very busy on a client project this week.

I wonder what is the difference between length mode and character mode I would have thought length is length in characters?

**Comment by JacobsDataSolutions** [comment]
Hey Joe, I'll do a pull of your branch and have a look at the failing test. I would be OK with leaving out character/length truncation modes. I lifted both of those out of Humanizer. The big difference between the two of them is that one counts whitespace and the other does not. I understand about being busy! All the best, - John

**Comment by joeaudette** [comment]
Unfortunately after further testing I've found using Word truncation also can produce invalid markup with various combinations of settings and content.

I don't think Humanizer is the right tool for the job of truncating html correctly. 

I will make an attempt to implement a truncation strategy using HtmlAgilityPak.

**Comment by joeaudette** [comment]
I've made some progress on this.

Basically using HtmlAgilityPack to check that the truncated content is valid, ie no parsing errors. If there are parsing errors I increment the truncation length by one and try again until I get a valid result. This can be problematic since strings are immutable and it is not desirable to do lots of string operations on a list of posts, so I introduced caching of the teaser to avoid doing it on every request of the list page.

I am logging the truncation retries as a warning to be visible in the log with a recommendation to create a specific teaser for the posts where retries are needed.

I still need to do some thinking and refactoring, I think the layering of ITeaserService, IContentProcessor, and IHtmlProcessor needs to be thought through and made cleaner and more clear what is going on when reading the code. Also need more work to handle teaser overrides, where I think we should use html/markdown editor and therefore conversion of markdown teaser to html needs to be factored in to the process.

Will get back to this when I can but other priorities are constraining me.

**Comment by JacobsDataSolutions** [comment]
No problem. If your changes are checked into that branch then I'll do a pull and see what you did. I'm also starting to get slammed with side work, so no worries with timing. When I get a chance, I'll re-examine the code and see if I can come up with a more robust solution which doesn't require Humanizer.

**Comment by joeaudette** [comment]
Hi @JacobsDataSolutions ,
Actually after a bunch of refactoring I've merged the teaser branch to master this morning. Still have some things to do before I will publish updated nugets. But you can have a look and try it out using the master branch. And let me know if you have any questions or feedback about the changes.

**Comment by joeaudette** [comment]
@JacobsDataSolutions nuget packages have now been released with the teaser functionality, so closing this issue

**Comment by JacobsDataSolutions** [comment]
@joeaudette Hey Joe, I updated my nuget packages and it looks great! Thank you for this. Please let me know if there is any other way I can contribute.
