### ISSUE TITLE
How not to delete posts/images when using nodb_storage and publishing again

### ISSUE THREAD

**Issue by iberodev** [joeaudette/cloudscribe.SimpleContent#75]
This is a general question about what approach to follow when using SimpleContent and adding posts

SCENARIO

- We have our WebApp with SimpleContent, no_db, etc.

- The blog posts are stored under nodb_storage.

- Once in production we use OLW to create new posts/images

- We version the code with Git source control

- Pushing changes to master branch will trigger a new publish of the whole application

The problem I see is that the Git repository will not be aware of new posts published through Open Live Writer.
If another developer clones the Web app repository, makes some changes and pushes changes to master triggering a new publish, wouldn't the content of `nodb_storage` be deleted in production?

What would be the best approach to follow for that scenario?

One option I can think of is running the WebApp in local so that we can use Open Live Writer to publish always locally (OLW attached to the localhost Metaweb API), and after that pushing the new changes to the source control so that everything what's in local is also in source control and in production.

**Is there any other approach?**

**Comment by joeaudette** [comment]
It is a challenging problem. Honestly I think the solution you mentioned is the most straight forward approach to keep things flowing in one direction only from git to production.

> If another developer clones the Web app repository, makes some changes and pushes changes to master triggering a new publish, wouldn't the content of nodb_storage be deleted in production?

I think that is most likely but depends on your environment. The files could live on disk as unversioned files, but in a web farm scenario where new nodes are provisioned based on git, then typically when a push to git triggers a new deployment it creates a new web farm node with the new files and the old node is de-provisioned so the files that are not part of git are lost. So maybe not explicitely deleted just lost because they are only on one node and not part of the state that builds new nodes.

Even with this approach, it does not solve all problems. Specifically consider if you have comments enabled those comments are part of the serialized post in production, ie the production copy of the post gets updated from the web front end when someone makes a comment. One solution is to just not allow comments. Another solution is to not use the internal comment system but instead use something like Disqus or IntenseDebate or some other external comment system. To do that would require customizing the views to remove the markup related to the internal comment system and add whatever is needed to plugin one of those systems. The default views are embedded but you can copy ones that you want to override into the appropriate folder under  Views and the local file will be used instead.

Other strategies I can think of include having some way to push new files and file changes from production back to git. Github for example has apis that would make it possible and I think most of the big online git providers have similar apis. There could be some component in production to watch the file system and push commits to the repo. I have also considered implementing an event system for create/update/delete etc which would allow people to plugin custom event handlers that can be triggered to run after those events happen so custom code could then push the changes to git. Even in the absence of an event handler system, one could plugin custom NoDb [IBasicCommands implementation](https://github.com/joeaudette/NoDb/blob/master/src/NoDb/BasicCommands.cs) that would both save to the file system and push to git. Similarly for files uploaded via OLW, they would be processed by IMediaProcessor, you could make a custom implementation based on [FileSystemMediaProcessor](https://github.com/joeaudette/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.Web/Services/FileSystemMediaProcessor.cs) that both saves to the file system and pushes to git.

**Comment by joeaudette** [comment]
and of course another strategy is to use EF Storage instead of NoDb, but that would still require some solution for uploaded files. the current solution stores media files on disk but perhaps some custom implementations could be created to store files in the db instead or blob storage somewhere. then of course the posts would need to be processed to change the urls or maybe some middleware could redirect media requests that are directed to the local filesystem to a different url
